### ISSUE TITLE
TypeError: Cannot read property 'line' of null

### ISSUE THREAD

**Issue by cinderblock** [hipstersmoothie/jest-github-reporter#74]
I'm getting an error running jest caused by `jest-github-reporter` when running on my local dev machine:

```log
TypeError: Cannot read property 'line' of null
    at .\node_modules\jest-github-reporter\src\create-check.ts:71:70
    at Array.forEach (<anonymous>)
    at _loop_2 (.\node_modules\jest-github-reporter\src\create-check.ts:67:25)
    at _loop_1 (.\node_modules\jest-github-reporter\dist\create-check.js:60:17)
    at createAnnotations (.\node_modules\jest-github-reporter\dist\create-check.js:74:13)
    at Object.default (.\node_modules\jest-github-reporter\src\create-check.ts:92:18)
    at GitHubReporter.<anonymous> (.\node_modules\jest-github-reporter\src\index.ts:9:22)
    at step (.\node_modules\jest-github-reporter\dist\index.js:33:23)
    at Object.next (.\node_modules\jest-github-reporter\dist\index.js:14:53)
    at .\node_modules\jest-github-reporter\dist\index.js:8:71
```

This error occurs when a promise based test throws an exception as far as I can tell

**Comment by joeyjiron06** [comment]
I am seeing this issue as well. any update on this? Would you take a PR to fix this issue?
